[package]
name = "steven_blocks"
version = "0.0.1"
authors = [ "Thinkofdeath <thinkofdeath@spigotmc.org>" ]

[dependencies]
lazy_static = "0.2.*"
cgmath = "0.12.*"
collision = "0.9.0"


[dependencies.steven_shared]
path = "../shared"
version = "0"
